###
POST http://localhost:3004/api/course-service/v1/course/new?api_key=wGlWnNDcrU0K4zOF8ywGl HTTP/1.1
content-type: application/json

{
    "code": 321987321,
    "name":"Subject E",
    "credits": 12,
    "description": "This is a description of the subject ABC",
    "prerequisite": ["643e2d1357b93e5a82ddc838"],
    "departmentAllowed": "213298731"
}
