http:
    port: 8888
admin:
    port: 9876
    host: localhost

apiEndpoints:
    account-server:
        host: localhost
        paths:
            - "/api/account-service/*"
    subject-server:
        host: localhost
        paths:
            - "/api/docs/*"
serviceEndpoints:
    account-server:
        url: "http://localhost:3939/"
    subject-server:
        url: "http://localhost:3300"
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
    - jwt:
          algorithm: HS256
          secretOrPublicKey: "kQp0VQ2CUC"
          expiresIn: 5
          notBefore: 0
          audience: myApp
          issuer: myApp
    - jwt-refresh:
          action:
              jwt:
                  secretOrPublicKey: "kQp0VQ2CUC"
              refresh:
                  refresh_secret: "rDqyBRoUhA"
                  refresh_ttl: 3600 # thời gian sống của token mới được tạo ra, tính bằng giây
                  refresh_cookie: "refresh_token" # tên của cookie để chứa mã thông báo làm mới
                  refresh_url: "/auth/refresh" # đường dẫn API để thực hiện làm mới token
pipelines:
    account-server:
        apiEndpoints:
            - account-server
        policies:
            - jwt: # secure API with key auth
            - proxy:
                  - action:
                        serviceEndpoint: account-server
                        changeOrigin: true

    subject-server:
        apiEndpoints:
            - subject-server
        policies:
            - proxy:
                  - action:
                        serviceEndpoint: subject-server
                        # changeOrigin: true
