http:
  port: 8888
admin:
  port: 9876
  host: localhost
  
apiEndpoints:
  account-server:
    host: localhost
    paths:
      - '/api/account-service/*'
  subject-server:
    host: localhost
    paths:
      - '/api/docs/*'
serviceEndpoints:
  account-server:
    url: 'http://localhost:3939/'
  subject-server:
    url: 'http://localhost:3300'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
  - jwt
pipelines:
  account-server:
    apiEndpoints:
      - account-server
    policies:
      - jwt: # secure API with key auth
        - action:
            secretOrPublicKey: "123123"
            checkCredentialExistence: true
            issuers:
              - myIssuer
            audiences:
              - myAudience
            algorithms:
              - HS256
      - proxy:
          - action:
              serviceEndpoint: account-server
              changeOrigin: true

  subject-server:
    apiEndpoints:
      - subject-server
    policies:
      # - rate-limit:
      #   - action:
      #       max: 10
      #       windowMs: 12000
      - proxy:
          - action:
              serviceEndpoint: subject-server
              # changeOrigin: true
